### ISSUE TITLE
S04-1 Petri hálók

### ISSUE THREAD

**Issue by dobreffandras** [rockkid777/pti-msc-2015-zv#10]
Párhuzamos folyamatok modellezése Petri hálók segítségével. Petri hálók definíciója és működési szabálya. Párhuzamos folyamatok legfontosabb viselkedési tulajdonságai (elevenség, biztonságosság, korlátosság) és azok vizsgálatára szolgáló eszközök (elérési, fedési fa). Petri doboz alkalmazása párhuzamos folyamatok modelljének felépítésében. Párhuzamos és elosztott rendszerek szemantikai leírása lehetséges formáinak (műveleti, leíró, axiomatikus) bemutatása egy konkrét példán keresztül.

**Comment by varjujan** [comment]
Elkezdtem ehhez egy, az eddigi 2 oldalasnál kicsit bővebb, de mégsem "Tejfel összes diája" hosszúságú kidolgozást.

**Comment by balintkissdev** [comment]
@rockkid777 , légyszi assign-old az issue-hoz @varjujan -t hogy követkető legyen. Tudom hogy mindjárt kész, de így követhető hogy ki csinálta a tételt, kihez kell fordulni mint "felelős" ha review-zni kell.
