### ISSUE TITLE
S04-2 Elosztott alkalmazások készítése

### ISSUE THREAD

**Issue by dobreffandras** [rockkid777/pti-msc-2015-zv#11]
Többrétegű architektúra, elosztott szerveroldal. Kommunikációs eszközök: távolieljárás-hívás és üzenet alapú infrastruktúra (point-to-point és publish-subscribe modell). Névszolgáltatás. Enterprise JavaBeans komponensmodell, EJB-k fajtái. Beanek életciklusa. Dependency injection. Elosztott és globális tranzakciók.

**Comment by balintkissdev** [comment]
Átírtam a címet, mert "Többrétegű architektúra, elosztott szerveroldal" az csak a tétel egyik része.

**Comment by dobreffandras** [comment]
Hát igen... Címet adhattak volna a tételeknek.

**Comment by balintkissdev** [comment]
@rockkid777 , légyszi assign-old az issue-hoz @varjujan -t hogy követhető legyen. Tudom hogy mindjárt kész, de így látható hogy ki csinálta a tételt, kihez kell fordulni mint "felelős" ha review-zni kell.

**Comment by rockkid777** [comment]
@balintkiss501 még várunk, hogy @varjujan elfogadja a felkérést. 🙂

**Comment by varjujan** [comment]
Bocsi, valamiért elsiklottam az invite felett :)
