### ISSUE TITLE
S04-3 Többszálú programok, a Java nyelv szinkronizációs eszközei

### ISSUE THREAD

**Issue by dobreffandras** [rockkid777/pti-msc-2015-zv#12]
Többszálú programok ütemezése. A Java nyelv szinkronizációs eszközei. Jól szinkronizált programok, a happens-before reláció. Data race és race condition fogalma. Konkurrens használatra tervezett adatszerkezetek. Szinkronizáló osztályok. Szálak és feladatok. Félbeszakíthatóság. Haladási problémák (holtpont, kiéheztetés, livelock, priority inversion).

**Comment by balintkissdev** [comment]
Én csinálom.
