### ISSUE TITLE
Markdown konvenciók Pandoc generáláshoz

### ISSUE THREAD

**Issue by balintkissdev** [rockkid777/pti-msc-2015-zv#16]
Ez az issue működhet ilyen "wishlist"-ként, hogy mi kerülhetne a README "Konveciók" része közé. Miközben javítottam az s04-3 tételem Markdown-ját, kipróbáltam pandoc-al való generálással és a következőkre jutottam.:

1. Pandoc csak úgy képes felismerni TeX-szintaxisú képleteket ha a $ jel után nincsen szóköz. Sima $ inline képletet csinál, dupla $$ külön paragrafusba illeszti.

```
Good (no space):
ha $hb(a, b)$ és $hb(b, c)$ akkor $hb(a, c)$

Good (no space):
$$hb = (po \cup sw)^+$$

Bad! (spaces)
ha $ hb(a, b) $ és $ hb(b, c) $ akkor $ hb(a, c) $

Bad! (spaces)
$$ hb = (po \cup sw)^+ $$
```

2. Használj soft tabokat (szóköz) hard tabok helyett (tab karakter). Pandoc 4 szóköz alapján tud nested listákat csinálni.

```
Good (4 space):
* Nem állíthat le egy szál egy másik még futásban lévő szálat, de megszakító kérést küldhet neki, amire a futásban lévő
  szál  megáll és átadja a vezérlést.
* Ezt egy kontextusváltás keretében teszi, mely magába foglalja a szál
    + stack-jének ürítését,
    + processzor regisztereinek ürítését,
    + cache ürítését
    + és a program counter elmentését. Ezután tölti be a másikét.
* Interrupt hívásakor beállítódik egy interrupt flag a szálban, ami lekérdezhető `interrupted()` és `isInterrupted()`
  segítségével.

Bad (2 space)!
* Nem állíthat le egy szál egy másik még futásban lévő szálat, de megszakító kérést küldhet neki, amire a futásban lévő
  szál  megáll és átadja a vezérlést.
* Ezt egy kontextusváltás keretében teszi, mely magába foglalja a szál
  + stack-jének ürítését,
  + processzor regisztereinek ürítését,
  + cache ürítését
  + és a program counter elmentését. Ezután tölti be a másikét.
* Interrupt hívásakor beállítódik egy interrupt flag a szálban, ami lekérdezhető `interrupted()` és `isInterrupted()`
  segítségével.
```

Extrák:
* Szintaktikus elemek ` jelek közé kerülhet
* Tétel elején tartalomjegyzék
* Tétel végén opcionális külső források ahol utána lehet olvasni egyszer a fogalmaknak hogy jobban megértse az ember

Ide még jöhetnek ötletek.

**Comment by dobreffandras** [comment]
Köszi szépen az infókat. :)

Most már legalább ketten vagyunk, akik szerint az _Extrák_ alatt felsoroltak szükségesek a megfelelő minőségi szint eléréséhez.

**Comment by rockkid777** [comment]
Én is nagyon adom, csak nem akartam alapértelmezettnek beadni, nehogy elijesszek jelentkezőket. Így aztán esetleges utólgos formátum javításokat vállalok. 😄  De nagyon köszi, hogy figyeltek rá! 👍

**Comment by balintkissdev** [comment]
\+ Tesztelés commit előtt: pandoc-al generáld le a saját .md fájlod és figyeld meg a formázást, ugyanis a PDF eredmény lesz a mérvadó, nem a GitHub felületen lévő Markdown megjelenítés.

pandoc tetel.md -o tetel.pdf

**Comment by rockkid777** [comment]
Itt csak annyival szólnék bele, hogy a githubé is számít, de amint odaértem, tényleg megcsinálom a web-re generálást. 🙂

**Comment by balintkissdev** [comment]
Rendben, figyelembe veszem azt is.

**Comment by balintkissdev** [comment]
Még egy javaslat: diagramokat lehet draw.io-ban rajzolni: https://www.draw.io/

**Comment by balintkissdev** [comment]
Becsuktam, mert minek van nyitva.
