### ISSUE TITLE
S00-1 Szintézis és verifikáció (Programozás elmélet)

### ISSUE THREAD

**Issue by balintkissdev** [rockkid777/pti-msc-2015-zv#22]
* Programozási alapfogalmak: feladat, program, megoldás (parciális és teljes helyesség).
* Elemi programok (üres, értékadás) és program konstrukciók (szekvencia, elágazás, ciklus, atomi utasítás, várakozó utasítás, párhuzamos blokk) definíciói.
* Nem-determinisztikus strukturált  programok valamint párhozamos programok  formális  verifikációja  (A  helyesség-vizsgálati  módszerek  menete,  a  nevezetes  programszerkezetek helyességének  szabályai.) 
* Az interferencia-mentesség és a holtpont-mentesség (Owicki-Gries) vizsgálata.
* A kölcsönös kizárás és megvalósítása.

**Comment by dobreffandras** [comment]
Ezt bevállalom :D
