### ISSUE TITLE
S00-4 Nyelvek típusrendszere

### ISSUE THREAD

**Issue by balintkissdev** [rockkid777/pti-msc-2015-zv#24]
* Absztrakt szintaxisfák, absztrakt kötéses fák, levezetési fák.
* Szintaxis, típusrendszer, operációs szemantika.
* Típusrendszer és operációs szemantika kapcsolata: haladás és típusmegőrzés tétele.
* Magasabbrendű függvények, Church típusrendszere.
* Let kifejezések.
* Szorzat és összeg típusok.
* Induktív típusok: Bool, természetes számok.
* Polimorfizmus (System F), absztrakt típusok.
* Altípus.

**Comment by balintkissdev** [comment]
Ez a tantárgyam négyes lett Ambrusnál. Tudok benne segíteni, de már túl vagyok terhelve.

**Comment by varjujan** [comment]
@balintkiss501 Annyit meg tudnál mondani, hogy az Ambrus oldalán lévő [jegyzet](https://akaposi.github.io/tipusrendszerek/jegyzet.pdf) elegendő ZV-re? Mert ha igen, akkor kiírhatom belőle a lényeget.

**Comment by rockkid777** [comment]
Sajna nekem is csak négyes, viszont azóta is foglalkozom a témával. 🙂

**Comment by varjujan** [comment]
@rockkid777 Szeretnéd akkor te elkészíteni a kidolgozást? Én még nem kezdtem el, kereshetek másik tételt.

**Comment by rockkid777** [comment]
@varjujan bocs, csak azt néztem, hogy van-e assignee. Szívesen elkészítem, de ha jobb szeretnéd, akkor átveheted. :)

**Comment by varjujan** [comment]
@rockkid777 Isten ments :) Nézek inkább egy másik tételt, amihez akár régebbről is van jegyzetem.

**Comment by balintkissdev** [comment]
@rockkid777 Találtam egy ingyenes ebook-ot (nem torrent). Még nem olvastam át, de ha valami laikusan van benne leírva, akkor ez segíthet téged. Továbbá forrásnak meg lehet jelölni a tételben.

https://www.cs.kent.ac.uk/people/staff/sjt/TTFP/ttfp.pdf

Akárcsak Ambrus jegyzetét, de ezt nem is kell mondanom.

https://akaposi.github.io/tipusrendszerek/jegyzet.pdf

**Comment by balintkissdev** [comment]
@varjujan 

> Annyit meg tudnál mondani, hogy az Ambrus oldalán lévő jegyzet elegendő ZV-re? Mert ha igen, akkor kiírhatom belőle a lényeget.

Úgy tudom igen. Csak másképp kell beszélni róla mint a tantárgy vizsgáján, hiszen Ambrus azt mondta, hogy itt a definíciók és fogalmak nagyobb szerepet kapnak.

**Comment by rockkid777** [comment]
@balintkiss501  Church típusrendszerét szerinted honnan kéne megszerezni? Lehet írok Ambrusnak.

**Comment by davidfarkas93** [comment]
@rockkid777 
Church (F1): http://people.inf.elte.hu/pgj/nytr_msc/nytr_msc_20150917.pdf (15.-30. dia)
Hasznos: https://akaposi.github.io/tipusrendszerek/

**Comment by rockkid777** [comment]
Kaposi jegyzetből néztem. Ambrus azt mondja a Church típusrendszere simán a magasabbrendű függvények típusrendszerea a 4.2-es részből.

**Comment by rockkid777** [comment]
Lassan kész vagyok vele, de szerintetek mennyire rakjak bele képleteket? Én még visszamenőleg is megritkítanám, mert nem az a lényeg, hogy azokat megjegyezze az ember (még vizsgán is külön ki voltak írva a szabályok egy lapra, hogy csak alkalmazni tudd).

**Comment by varjujan** [comment]
Szerintem maradhatnak benne, hogy legalább egyszer megnézhesse az ember, tanuláskor meg max simán átugorja

**Comment by dobreffandras** [comment]
Hm, jól értem akkor, hogy a **Magasabbrendű függvények**, a **Church típusrendszere** és az **F1 típusrendszer** egymás szinonimái?

**Comment by balintkissdev** [comment]
@dobreffandras Gőzöm nincs, rákerestem Google-ben de szétsült az agyam. Ez nekem már ezotéria. A végén formális kategóriaelmélettel fogunk szellemeket idézni.

@rockkid777 ?

**Comment by dobreffandras** [comment]
XD Nekem is felforrt már az agyam. Ez a tétel bődületesen nagy, pedig most jócskán hagytam ki belőle részeket.

**Comment by rockkid777** [comment]
Igen, elvileg ugyanazt takarják. (Nekem is ez jött ki.)
