### ISSUE TITLE
S01-5 Projektirányítás az informatikában

### ISSUE THREAD

**Issue by balintkissdev** [rockkid777/pti-msc-2015-zv#25]
* Informatikai  projektek  specialitásai  és  típusai.
* A projekt  politikai,  gazdasági  és  jogi  környezete.
* Vállalati  szintű  tervezés,  vállalatok  életciklusai.
* Projekt  szervezet  felépítése.
* A projekt  életciklusa.
* Projekttervezés:  feladat  és  szervezet  lebontási  struktúra;  időelemzés,  kritikus  út  meghatározása, erőforrás-ütemezés, költségvetés hozzárendelése, kritikus lánc módszer.
* A projektet kísérő folyamatok.
* Projektirányítási  módszertanok  (Prince,  PMBOK  CMM  és  CMMI).
* Projektirányítás  emberi vonatkozásai.

**Comment by dobreffandras** [comment]
Ezt bevállalom :D

**Comment by dobreffandras** [comment]
Elég furcsa ez a tétel, de valamennyire sikerült kidolgoznom. Viszont a "A projekt politikai, gazdasági és jogi környezete" pontra egyszerűen semmi forrást nem találtam a diasorban. Van gazdasági téma a 2. előadáson, de az vállalatra vonatkozó, és a tartalomjegyzékben van "jogi vonatkozás", de az már volt a tananyag része.

Van esetleg valakinek valami javaslata?

**Comment by davidfarkas93** [comment]
Én ennyit találtam egy korábbi kidolgozásban. Szerintem ennyi bőven elég erről a témáról.

Politikai környezet:
A vállalatokra közvetett hatással van a politikai környezet amelyben a vállalat él.
A politikai környezet tényezői:
- politikai stabilitás
- a politika beleszól a gazdaságba
- a politika döntéshozatal helyszínei (parlament, kormány, önkormányzat)
- a hatalmi ágak és azok együttműködése
A vállalat számára nem mindegy, hogy a konzervatív, liberális vagy szocialista irányelvek dominálnak

 Gazdasági környezet:
- már közvetlenül befolyásolja a vállalat életét.
- világgazdasági helyzet, haza gazdasági helyzet, gazdasági növekedés, infláció, beruházási kedv, koncepció
- az informatikai ipar érzékeny a gazdasági helyzet, mert ha nem megy a gazdaság, akkor a gazdálkodó szervek rendszerint az informatikai kiadásokon kezdenek el takarékoskodni
- a munkanélküliség rossz, de rövid távon a vállalatok hasznot húzhatnak belőle, mert könnyebb munkaerőt találni

A jogi környezet:
- egy-egy jogszabályhoz való alkalmazkodáshoz időre van szüksége a szervezeteknek

**Comment by varjujan** [comment]
Szerintem jó az amit @farkasdav93 ír, de szerintem abba se hal bele senki, ha kihagyod. Én például nem is találok ilyesmiről semmit a vizsgára készített jegyzetemben, nem hiszem, hogy olyan fontos lett volna.

**Comment by davidfarkas93** [comment]
@varjujan Egyet értek. Én sem gondolom, hogy bárki a vizsgán pont ezt fogja megkérdezni, ha kimarad :D

**Comment by balintkissdev** [comment]
@dobreffandras @varjujan @farkasdav93 Én csak Gazdaságinformatikus Bsc-s múltamból tudok beszélni, de meg lehetne említeni a SWOT-analízist, amit vállalkozások kockázatainak felmérésére használnak.

SWOT: Strengths-Weaknesses-Opportunities-Threats

* Erősségek (strengths): Pozitív belső vállalati tényezők, amik a vállalkozás előnyei és fejleszthetjük
* Gyengesége( weaknesses): Negatív belső vállalati tényezők, amik a vállalkozás hátrányai és javíthatunk rajta
* Lehetőségek (opportunities): Pozitív külső politikai- vagy gazdasági tényezők, amiket nem tudunk befolyásolni, de kihasználhatjuk előnyként
* Veszélyek (threats): Negatív külső politikai- vagy gazdasági tényezők, amiket nem tudunk befolyásolni, de fel kell készülnünk rájuk

Ez egy suggestion, lőjetek le ha túl sok.

**Comment by dobreffandras** [comment]
Okés, akkor ezzel még kiegészítem és nyitok erről is PR-t. 

(Igen, pont ezért írtam, hogy furcsa a tétel, mert olyan dolgok vannak benne, amik nem relevánsak.)
