### ISSUE TITLE
S01-6 Szoftverfejlesztési modellek

### ISSUE THREAD

**Issue by balintkissdev** [rockkid777/pti-msc-2015-zv#26]
* Szoftverfejlesztési modellek (vízesés, spirális, evolúciós, RUP, XP, xUML).
* Architekturális minták és  hatásuk  a  rendszer  minőségi  jellemzőire.
* Tervezési  minták  (GoF,  valamint  3  további  létrehozási minta).
* Konkurens minták.
* Antiminták, újratervezési minták.

**Comment by davidfarkas93** [comment]
Ezt elvállalom, és akkor ezzel beszállnék és is a kidolgozásba.

**Comment by varjujan** [comment]
A 2015-ös tételsor alapján vizsgázol? Csak mert függőben van egy emailem jelenleg Kozsiknál és a tárgy oktatóinál a tétellel kapcsolatban, mivel akik már Kovács Attilánál végezték ezt a tárgyat (Tervezés és elemzés), azok ennek csak egy részét tanulták hivatalosan. Szóval elképzelhető, hogy a '15-ös verzióban még változik ez a tétel.

Ha így is kidolgoznád, hajrá! :)

**Comment by davidfarkas93** [comment]
'15-ös alapján vizsgázok, de ha még változhat akkor hagyom egy darabig.

**Comment by balintkissdev** [comment]
@farkasdav93 Herzlich Wilkommen!

@varjujan Én is Attilánál végeztem a tárgyat. Valószínű akkor, hogy a Design Pattern-es rész ki lesz dobva és a követelményelemzés/projektvezetés/menedzsmentes része lesz előnyben részesítve. Ennyivel könnyebb lesz.

**Comment by davidfarkas93** [comment]
Lehet, hogy én keverem egy másik tárgyal, de mintha első két előadáson beszélt volna a modellekről...

**Comment by varjujan** [comment]
Sajnos a mai emlékeztető levelemre se érkezett válasz eddig. Hétfőn írok még egyet, de ha kedd éjfélig sem nyilatkoznak, akkor muszáj lesz ennél a tematikánál maradnunk. 
Van egy [korábbi kidolgozás](https://docs.google.com/document/d/1NzKkte77HNPQTUynEswsmDF1MOFwdPEY3Nkf9rdMR6Y/edit), ez 1 hét alatt bőven átírható/kiegészíthető és megtanulható.

**Comment by varjujan** [comment]
Nem úgy tűnik, hogy nagyon érdekelné Kozsikot és a tárgy felelősét, hogy ezt tanultuk-e. Valószínűleg ez a tematika marad.

**Comment by dobreffandras** [comment]
Nem tudom, hogy akarjuk-e tartani magunkat a kedd éjfélig, vagy akkor inkább kezdjük-e el.

@farkasdav93 továbbra is áll a felajánlás? Azt is csinálhatjuk, hogy felosztjuk. Nekem valamennyire testhezálló a téma (Modellek, xUML, GoF), bár valóban van olyan, amiről az életben nem hallottam még. 

K. Attilánál az egész tárgy követelményelemzésről szólt. A vendégelőadók közül volt olyan, aki xUML-ről mesélt, de a többi is inkább menedzsment volt. (Volt ugye egy Startup-os vendég [Samebug.io egyébként], egy Angster Erzsébet féle rule-based design, egy Business Analyst-es előadás, meg Asztalos Domonkos - xUML)

**Comment by davidfarkas93** [comment]
Én kb biztos vagyok benne, hogy holnap éjfélig sem fog változni a helyzet még ha válaszolnak is. 
@dobreffandras Már korábban kiegészítettem egy korábbi kidolgozást néhány plusz dologgal, amit bedobhatok, aztán review-ba hozzá dobhatod amit még pluszba gondolsz.

**Comment by dobreffandras** [comment]
@farkasdav93 Okés, tedd fel, amid van, aztán meglátjuk.

**Comment by varjujan** [comment]
Nyugodtan feltehetitek ami van, ha őket se érdekli, minket se zavarjon miből felelünk. Nekem a régi kidolgozás alapján az egyik legkönnyebb tételnek tűnt ez, még így is, hogy egy részét nem vettük hivatalosan.

**Comment by szdominik** [comment]
Aki esetleg erre a tematikára készülne, itt a Sike-tárgy jegyzete:
http://people.inf.elte.hu/sike/TervElem/tervelem.pdf
