### ISSUE TITLE
S01-8 Komponens alapú szoftverfejlesztés 2

### ISSUE THREAD

**Issue by balintkissdev** [rockkid777/pti-msc-2015-zv#28]
* Komponens  megvalósítása:  kölcsönhatás  modell,  viselkedési  vagy  algoritmikus  modell  és strukturális modell.
* Komponens megtestesítés: finomítás és fordítás, a normál objektum forma (NOF) fogalma,  komponensek  újrafelhasználása,  polcról  levett  komponensek,  rendszer  létrehozása komponensekből,  termékcsalád  fogalma.
* Rendszer  létrehozása  polcról  levehető  komponensekből.
* A burkoló és a híd fogalma, szerepük.

**Comment by davidfarkas93** [comment]
@varjujan  S01-2 helyett akkor bevállalom ezt, amíg tisztázódik annak a kérdése.
