### ISSUE TITLE
S01-9 Szoftverfejlesztés minőségi aspektusai

### ISSUE THREAD

**Issue by balintkissdev** [rockkid777/pti-msc-2015-zv#29]
* A szoftverminőség komplex kérdésköre, termék és folyamat alapú megközelítés.
* A szoftverfejlesztés és a tesztelés kapcsolata, V modell, agilitás.
* A tesztelés szintjei.
* A tesztelés életciklusa.
* Teszttervezési technikák.
* Specifikáció  alapú:  ekvivalencia-osztályozás,  határérték  elemzés,  döntési  táblák, állapotgépek,  használati  eset  tesztelés;  struktúra  alapú:  utasítás  és  döntési  lefedettség.
* Review technikák, statikus tesztelés.
* A tesztelés dokumentálása.
* Teszteszközök.

**Comment by davidfarkas93** [comment]
FYI elkezdtem kidolgozni

**Comment by balintkissdev** [comment]
@farkasdav93 Megvan az ISTQB könyv hozzá? El tudom küldeni ha kell.

**Comment by davidfarkas93** [comment]
köszi, de megvan

**Comment by dobreffandras** [comment]
A facebook csoportban is van egy kidolgozás, hátha segít:
https://www.facebook.com/groups/517544268380942/permalink/1036342529834444/

**Comment by dobreffandras** [comment]
@farkasdav93  a 6. fejezetben (Specifikáció alapú és Struktúra alapú tesztelés)  az összes példa a "specifikáció alapú" pont alatt van. Ez véletlen, vagy a struktúra alapúhoz nem volt forrás?
