### ISSUE TITLE
S02-1 Funkcionális nyelvek alapfogalmai

### ISSUE THREAD

**Issue by dobreffandras** [rockkid777/pti-msc-2015-zv#3]
Funkcionális nyelvek alapfogalmai: modell, kiértékelés, listák, curry-zés, magasabbrendű függvények, tisztaság. Típusok: algebrai adattípusok, típusosztályok, típuskonstruktorok, kindok. Monadikus programozás. Példák.

**Comment by balintkissdev** [comment]
Szívesen vállalom s04-3 után. Többi s02-vel az a baj, hogy nem csináltam meg a Szerződés-alapú tárgyat, Paradigmákat meg a régi tanterv szerint csináltam és csak beadandót készítettem.

**Comment by balintkissdev** [comment]
Most csinálom.
