### ISSUE TITLE
S02-2 Multiparadigma programozás és Haladó Java 1

### ISSUE THREAD

**Issue by balintkissdev** [rockkid777/pti-msc-2015-zv#30]
* Memóriakezelés: referencia- és érték-szemantika.
* Referenciakezelési technikák, Objektumok másolása, move-szemantika.
* Erőforrásbiztos programozás, RAII, destruktor és szemétgyűjtés.
* Kivételkezelés, kivételbiztos programozás.
* A konkurens programozás alapelemei Javában és C++-ban.

**Comment by varjujan** [comment]
Elkezdtem ehhez egy kidolgozást.
"Memóriakezelés: referencia- és érték-szemantika." Jól tudom, hogy ehhez nem volt külön előadás? (Nekem ez inkább BSc-s anyagnak hangzik) Jobb híján valami olyasmire gondoltam, mint ami ebben a diasorban van: [diasor](http://people.inf.elte.hu/groberto/elte_amp/eloadas_anyagok/elte_amp_ea08_eml.pdf). Esetleg van valakinek jobb ötlete?

**Comment by balintkissdev** [comment]
Porkoláb anyagai jutnak eszembe. Itt inkább "haladó C++" programozás kell, azaz már a C++11 újdonságai, mint a move szemantika és rvalue/lvalue különbségek.

Itt vannak a forrásaim amiket félév alatt könyvjelzőként összegyűjtöttem, de ez még nem sok:
http://aszt.inf.elte.hu/~gsd/multiparadigm/
http://gsd.web.elte.hu/multi/
http://en.cppreference.com/w/cpp/language/static_assert
http://thbecker.net/articles/rvalue_references/section_01.html

**Comment by balintkissdev** [comment]
Megnéztem a diasort, de úgy gondolom hogy ZV-n nem a Bsc-s háttértudásra kíváncsiak, hanem a Porkoláb tárgyán elhangzott C++ best practice-ekre.

**Comment by balintkissdev** [comment]
Jelezz ha kell benne segítség, mert én értek hozzá.

**Comment by varjujan** [comment]
Megoldom, csak elsőre nem tudtam pontosan belőni, melyik előadás anyagára kíváncsi memóriakezelés alatt.

**Comment by varjujan** [comment]
Visszavonom. Nekem ehhez sajnos nem elég összeszedettek Porkoláb diái, így egyelőre hanyagolom.

**Comment by balintkissdev** [comment]
Bevállalom. Nekem megvan a C++11-es domain tudásom, illetve expert wizard-class szintű Javás vagyok (na jó, Haladó Javát kettesre csináltam meg, de azóta megtanultam mit rontottam el).

**Comment by dobreffandras** [comment]
XD 🥇 
![](https://uproxx.files.wordpress.com/2014/03/wizardinstalls.png?w=200)

**Comment by balintkissdev** [comment]
@dobreffandras , ahogy Messengeren beszéltük, ha felszabadultál a review-k alól, akkor kéne segítség és fel kéne osztanunk ezt a tételt különben kifutunk az időből (még védésre is kéne prezit csinálni).

Én megcsinálom ezeket:

* Memóriakezelés: referencia- és érték-szemantika.
* Erőforrásbiztos programozás, RAII, destruktor és szemétgyűjtés.
* A konkurens programozás alapelemei Javában és C++-ban.

Neked pedig ez 

* Referenciakezelési technikák, Objektumok másolása, move-szemantika.
* Kivételkezelés, kivételbiztos programozás.

Te benne lennél ebbe?

**Comment by dobreffandras** [comment]
@balintkiss501 megfelel. Indíts egy branch-et az alap struktúrával (tartalomjegyzék + menüpontok) és akkor forkolok a tiedről.

**Comment by balintkissdev** [comment]
@dobreffandras Ez egy jó ötlet

**Comment by balintkissdev** [comment]
@dobreffandras 
https://github.com/balintkiss501/pti-msc-2015-zv/tree/s02-2

**Comment by balintkissdev** [comment]
Bocsi, mai délután VOLT fesztiválon vagyok, holnap pedig céges képzésen 9-től 17-ig. @dobreffandras , privátban tudok küldeni cuccot hogy gsd Multiparadigma óráján mit jegyzeteltem, az kiegészítésként szolgálhat.

**Comment by dobreffandras** [comment]
Az jó lenne, ha valamilyen formában el tudnád küldeni. Addig én igyekszem haladni. 

Jó bulit :D 🎉

**Comment by balintkissdev** [comment]
@dobreffandras csekkold a Messenger-ed.

Support keeps coming

**Comment by balintkissdev** [comment]
@dobreffandras Találtam újabb resource-ot:
https://github.com/AnthonyCalandra/modern-cpp-features

Látom a pull request-ed, de most céges képzésen vagyok. Csak átfutottam, de én még módosítanék rajta, majd elmondom mit ha hazaértem.

**Comment by balintkissdev** [comment]
Referencia- és érték-szemantika: heuréka

https://isocpp.org/wiki/faq/value-vs-ref-semantics
https://akrzemi1.wordpress.com/2012/02/03/value-semantics/
