### ISSUE TITLE
S02-3 Multiparadigma programozás és Haladó Java 2

### ISSUE THREAD

**Issue by balintkissdev** [rockkid777/pti-msc-2015-zv#31]
* Generikus programozás, típussal való paraméterezés, példányosítás és típustörlés.
* Absztrakt adatszerkezetek és algoritmusok.
* Konténerek és iterátorok.
* A C++ standard template könyvtár.
* Funktorok.
* Java annotációk.
* Önelemzés, osztálybetöltés.
* Objektumszerializáció.

**Comment by balintkissdev** [comment]
FYI: akinek Haladó Java-specifikus kidolgozásokhoz kell anyag, annak itt van a tavalyi Haladó Java vizsga kivonatom, ám hiányos.
https://drive.google.com/open?id=1zS7sAeQzSmJDqSA4RdAj8WNeLUw8fOMuMisXxfnX8nI

**Comment by davidfarkas93** [comment]
Tudja valaki, hogy itt amúgy a funktorok, konténerek, iterátorok, algoritmusok alatt az stl-ben (vagy is igazából az std-ben) levőkről kellene beszélni? csak mert ha igen akkor elég nyomorult sorrendben vannak megadva.

**Comment by balintkissdev** [comment]
@farkasdav93 Amikor én hallgattam a tárgyat, akkor Pataki Norbert tartotta az ezekről szóló előadásokat. És igen, STL-ről volt szó főképp.

http://aszt.inf.elte.hu/~gsd/multiparadigm/5_stl/PatakiNorbertSTL.pdf

**Comment by rockkid777** [comment]
Bocs, betegség, orvos miatt nem nagyon tudtam még haladni, még a másik tételem van folyamatban. Ha valaki hamarabb odaér, nekifoghat. Ha nem, akkor tolom. Bocsi srácok. 😕

**Comment by dobreffandras** [comment]
@varjujan @farkasdav93 nektek mennyi kapacitásotok van még? Talán ez lenne az utolsó tétel, amit terveztünk megcsinálni. (Ha jól vettem észre, akkor azoknak, akik beledolgoztak ebbe a projektbe a 3. és 5. blokk nem releváns.) Nem gond, ha nem fér már bele az időtökbe ez a tétel, csak tudjunk róla :)

**Comment by varjujan** [comment]
Háát én most álltam neki igazán tanulni a tételeket és egyelőre nem állok annyira jól, legkorábban talán a hétvégén tudnék foglalkozni vele. A legnagyobb bajom viszont az, hogy se Haladó Javahoz, se Multiparadigmához nincs teljes, részletes jegyzet (sőt Javahoz még diák se?), így max valami innen-onnan összehalászott dolgot tudnék csinálni (amit fogok is valószínűleg, ha jobb nem lesz), de azért felelősséget nem vállalnék.

**Comment by davidfarkas93** [comment]
Nekem sem nagyon lesz már rá időm :/

**Comment by balintkissdev** [comment]
Én most fejeztem be a diplomavédésem prezijét, munkahelyemen meg Haladó C++ képzésem van. Még a másik Multiparadigmás tételt se fejeztem be, ami miatt szégyellem magam.

**Comment by balintkissdev** [comment]
Ha be tudom fejezni a másik tételt, akkor be tudnám ezt is fejezni, de nem látok a jövőbe.

**Comment by szdominik** [comment]
Haladó Javánál az alaptémákhoz, pl. generic, ajánlott:
http://kitlei.web.elte.hu/segedanyagok/foliak/java/hu-java-bsc/
(De a szomszédos tételhez pl. a szemétgyűjtés is itt van.)

**Comment by davidfarkas93** [comment]
Mégis van rá időm, vagy is már kész csak be kell gépelnem. Nemsokára érkezik...
