### ISSUE TITLE
Kötelező blokkok

### ISSUE THREAD

**Issue by dobreffandras** [rockkid777/pti-msc-2015-zv#37]
Az első két blokkot (s00, s01) együtt vagy külön kezeljük? Ugye a tétel együtt kezeli, az issue-k viszont szét vannak szedve. Azért kérdezem, hogy egy mappa legyen és 1-9 legyen a számozás vagy két mappa külön számozással?

**Comment by balintkissdev** [comment]
Kettőre szavazok. Az érvelésem az, hogy így meg lehet különböztetni "Szopatós tudományos törzsanyagos S00" és "Lazább, menedzsmentes és tervezéses S01" tételeket.

**Comment by balintkissdev** [comment]
Ha pedig zavar hogy nem követné a számozás a tematikát, nyugodtan fel lehet rúgni a számozást és kezdődhet mondjuk S01-5-el az első S01-es tétel, aztán az issue-k számozását is át lehet írni. Ezzel aki nem ért velem egyet, az nyugodtan szólhat.

**Comment by dobreffandras** [comment]
Tetszik, várjuk meg a többiek javaslatát.

**Comment by varjujan** [comment]
Támogatom a javaslatot, legyen külön s00 és s01, de az s01 kezdődjön 5-től

**Comment by dobreffandras** [comment]
Akkor ez eldőlt.
