### ISSUE TITLE
S02-4 A szerződésalapú programtervezés

### ISSUE THREAD

**Issue by dobreffandras** [rockkid777/pti-msc-2015-zv#5]
A szerződésalapú programtervezés és -megvalósítás módszere, célja, szerepe. Szerződések leírását támogató nyelvi eszközök az Eiffel nyelvben. A szerződések formális jelentése Hoare-hármasokkal. A szerződések és a típusrendszer viszonya. Szerződések és objektum-orientáltság: öröklődés és felüldefiniálás. Üres referenciák. Kivételek.

**Comment by dobreffandras** [comment]
Ezt bevállalom :D

**Comment by varjujan** [comment]
A tétel neve kicsit megtévesztő, a '15-ös tételsorban ez már az S02-4

**Comment by balintkissdev** [comment]
@varjujan Editáltam a címet.
